In [1]:
import pandas as pd
import nltk 
import re

In [2]:
csv_file_path = "data.csv"
df = pd.read_csv("data.csv")
df

,Email,Phone,Address,URLs,Institute,About
0,l1f20bscs0001@ucp.edu.pk,0423-1234567,123 Main Street,www.example.com,Stanford University,This is John Doe. I am a software engineer. I ...
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,This is Jane Doe. <p>I am a doctor.</p> I like...
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>Hi I'm <strong>Emma Roberts</strong>. I'm p...
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>Hey there! I'm <strong>Liam Carter</strong>...
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>Hello I'm <strong>Ava Collins</strong>. I'm...
...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,G'day! I'm Sophia Martin. I'm pursuing a degre...
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,Hi there! I'm Liam Jackson. I'm studying compu...
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,Hello I'm Ava Moore. I'm studying architectur...
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,Bonjour! Je m'appelle Logan Thompson. J'étudie...
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,Ciao! I'm Mia Walker.<p> I'm studying economic...

#### 1.	Remove a valid email address. (l1f20bscs0001@ucp.edu.pk)

In [3]:
def remove_email(email):
    target_email = r'\w\d\w\d{2}\w{4}\d{4}@ucp\.edu\.pk'
    email_pat = re.compile(target_email)
    return re.sub(email_pat, '(Valid email Removed)', email)

In [4]:
df['Email'] = df['Email'].apply(remove_email)
df

,Email,Phone,Address,URLs,Institute,About
0,(Valid email Removed),0423-1234567,123 Main Street,www.example.com,Stanford University,This is John Doe. I am a software engineer. I ...
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,This is Jane Doe. <p>I am a doctor.</p> I like...
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>Hi I'm <strong>Emma Roberts</strong>. I'm p...
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>Hey there! I'm <strong>Liam Carter</strong>...
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>Hello I'm <strong>Ava Collins</strong>. I'm...
...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,G'day! I'm Sophia Martin. I'm pursuing a degre...
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,Hi there! I'm Liam Jackson. I'm studying compu...
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,Hello I'm Ava Moore. I'm studying architectur...
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,Bonjour! Je m'appelle Logan Thompson. J'étudie...
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,Ciao! I'm Mia Walker.<p> I'm studying economic...

#### 2.	Remove all the URLs from a given text

In [5]:
def remove_urls(text):
    url_pattern = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    return re.sub(url_pattern, '', text)

In [6]:
df['URLs'] = df['URLs'].apply(remove_urls)
df

,Email,Phone,Address,URLs,Institute,About
0,(Valid email Removed),0423-1234567,123 Main Street,www.example.com,Stanford University,This is John Doe. I am a software engineer. I ...
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,This is Jane Doe. <p>I am a doctor.</p> I like...
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>Hi I'm <strong>Emma Roberts</strong>. I'm p...
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>Hey there! I'm <strong>Liam Carter</strong>...
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>Hello I'm <strong>Ava Collins</strong>. I'm...
...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,G'day! I'm Sophia Martin. I'm pursuing a degre...
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,Hi there! I'm Liam Jackson. I'm studying compu...
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,Hello I'm Ava Moore. I'm studying architectur...
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,Bonjour! Je m'appelle Logan Thompson. J'étudie...
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,Ciao! I'm Mia Walker.<p> I'm studying economic...

#### 3.	Check phone number in a specific format (e.g. 0423-1234567).

In [7]:
def check_phone_number(text):
    phone_pattern = re.compile(r'0\d{3}-\d{7}')
    match = re.search(phone_pattern, text)
    if match:
        return True
    else:
        return False

In [8]:
df['Has_Phone_Number'] = df['Phone'].apply(check_phone_number)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number
0,(Valid email Removed),0423-1234567,123 Main Street,www.example.com,Stanford University,This is John Doe. I am a software engineer. I ...,True
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,This is Jane Doe. <p>I am a doctor.</p> I like...,False
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>Hi I'm <strong>Emma Roberts</strong>. I'm p...,True
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>Hey there! I'm <strong>Liam Carter</strong>...,True
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>Hello I'm <strong>Ava Collins</strong>. I'm...,True
...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,G'day! I'm Sophia Martin. I'm pursuing a degre...,True
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,Hi there! I'm Liam Jackson. I'm studying compu...,True
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,Hello I'm Ava Moore. I'm studying architectur...,True
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,Bonjour! Je m'appelle Logan Thompson. J'étudie...,True
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,Ciao! I'm Mia Walker.<p> I'm studying economic...,True

#### 4.	Find all the words that start with a capital letter in a sentence and convert them to lower case

In [9]:
def convert_capital_to_lower(text):
    word_pattern = re.compile(r'\b[A-Z][a-z]*\b')
    words = re.findall(word_pattern, text)
    for word in words:
        text = text.replace(word, word.lower())
    return text

In [10]:
df['About'] = df['About'].apply(convert_capital_to_lower)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number
0,(Valid email Removed),0423-1234567,123 Main Street,www.example.com,Stanford University,this is john doe. i am a software engineer. i ...,True
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,this is jane doe. <p>i am a doctor.</p> i like...,False
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True
...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True

#### 5.	Replace all occurrences of a specific word with another word in a given text

In [11]:
def remove_word(text):
    return re.sub('this is', 'I am', text)

In [12]:
df['About'] = df['About'].apply(remove_word)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number
0,(Valid email Removed),0423-1234567,123 Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True
1,jane.doe@example.com,555-666-7777,456 Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False
2,emma.roberts@example.com,0421-9876543,321 Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True
3,liam.carter@example.com,0331-3456789,654 Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True
4,ava.collins@example.com,0322-8765432,987 Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True
...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,876 Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True
105,liam.jackson@example.com,0425-3456789,321 Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True
106,ava.moore@example.com,0336-8765432,654 Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True
107,logan.thompson@example.com,0407-2345678,987 Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True
108,mia.walker@example.com,0418-7654321,234 Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True

#### 6.	Remove all the numbers from a string.

In [13]:
def remove_numbers(text):
    number_pattern = re.compile(r'\d+')
    return re.sub(number_pattern, '', text)

In [14]:
df['Address'] = df['Address'].apply(remove_numbers)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number
0,(Valid email Removed),0423-1234567,Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True
1,jane.doe@example.com,555-666-7777,Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False
2,emma.roberts@example.com,0421-9876543,Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True
3,liam.carter@example.com,0331-3456789,Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True
4,ava.collins@example.com,0322-8765432,Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True
...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True
105,liam.jackson@example.com,0425-3456789,Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True
106,ava.moore@example.com,0336-8765432,Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True
107,logan.thompson@example.com,0407-2345678,Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True
108,mia.walker@example.com,0418-7654321,Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True

#### 7.	Find and remove all the HTML tags in an HTML document.

In [17]:
def remove_html_tags(text):
    # Remove HTML tags using NLTK's HTML parser
    pattern = r'<[^>]+>'
    clean_text = re.sub(pattern,'', text)
    return clean_text

# Apply the function to the 'Text' column
df['Clean Text'] = df['About'].apply(remove_html_tags)

df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number,Clean Text
0,(Valid email Removed),0423-1234567,Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True,I am john doe. i am a software engineer. i lik...
1,jane.doe@example.com,555-666-7777,Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False,I am jane doe. i am a doctor. i like to read b...
2,emma.roberts@example.com,0421-9876543,Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True,hi i'm emma roberts. i'm pursuing a degree in ...
3,liam.carter@example.com,0331-3456789,Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True,hey there! i'm liam carter. i'm majoring in bu...
4,ava.collins@example.com,0322-8765432,Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True,hello i'm ava collins. i'm studying film produ...
...,...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True,g'day! i'm sophia martin. i'm pursuing a degre...
105,liam.jackson@example.com,0425-3456789,Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True,hi there! i'm liam jackson. i'm studying compu...
106,ava.moore@example.com,0336-8765432,Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True,hello i'm ava moore. i'm studying architectur...
107,logan.thompson@example.com,0407-2345678,Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True,bonjour! je m'appelle logan thompson. j'étudie...
108,mia.walker@example.com,0418-7654321,Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True,ciao! i'm mia walker. i'm studying economics a...

#### 8.	Extract all the words ending with "ing" in a sentence

In [19]:
def extract_words_ending_with_ing(sentence):
    pattern = r'\b\w+ing\b'  
    matches = re.findall(pattern, sentence)
    return matches

In [20]:
df['Words ending with "ing"'] = df['About'].apply(extract_words_ending_with_ing)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number,Clean Text,"Words ending with ""ing"""
0,(Valid email Removed),0423-1234567,Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True,I am john doe. i am a software engineer. i lik...,[]
1,jane.doe@example.com,555-666-7777,Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False,I am jane doe. i am a doctor. i like to read b...,[]
2,emma.roberts@example.com,0421-9876543,Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True,hi i'm emma roberts. i'm pursuing a degree in ...,"[pursuing, writing]"
3,liam.carter@example.com,0331-3456789,Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True,hey there! i'm liam carter. i'm majoring in bu...,[majoring]
4,ava.collins@example.com,0322-8765432,Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True,hello i'm ava collins. i'm studying film produ...,"[studying, creating]"
...,...,...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True,g'day! i'm sophia martin. i'm pursuing a degre...,[pursuing]
105,liam.jackson@example.com,0425-3456789,Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True,hi there! i'm liam jackson. i'm studying compu...,"[studying, engineering, playing]"
106,ava.moore@example.com,0336-8765432,Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True,hello i'm ava moore. i'm studying architectur...,"[studying, building]"
107,logan.thompson@example.com,0407-2345678,Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True,bonjour! je m'appelle logan thompson. j'étudie...,[]
108,mia.walker@example.com,0418-7654321,Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True,ciao! i'm mia walker. i'm studying economics a...,"[studying, traveling]"

#### 9.	Remove all whitespace characters from a string.

In [21]:
def remove_whitespace(text):
    pattern = r'\s'  
    clean_text = re.sub(pattern, '', text)
    return clean_text

In [23]:
df['Clean Text'] = df['About'].apply(remove_whitespace)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number,Clean Text,"Words ending with ""ing"""
0,(Valid email Removed),0423-1234567,Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True,Iamjohndoe.iamasoftwareengineer.iliketoplaybas...,[]
1,jane.doe@example.com,555-666-7777,Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False,Iamjanedoe.<p>iamadoctor.</p>iliketoreadbooksa...,[]
2,emma.roberts@example.com,0421-9876543,Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True,<p>hii'm<strong>emmaroberts</strong>.i'mpursui...,"[pursuing, writing]"
3,liam.carter@example.com,0331-3456789,Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True,<p>heythere!i'm<strong>liamcarter</strong>.i'm...,[majoring]
4,ava.collins@example.com,0322-8765432,Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True,<p>helloi'm<strong>avacollins</strong>.i'mstud...,"[studying, creating]"
...,...,...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True,g'day!i'msophiamartin.i'mpursuingadegreeinbiol...,[pursuing]
105,liam.jackson@example.com,0425-3456789,Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True,hithere!i'mliamjackson.i'mstudyingcomputerengi...,"[studying, engineering, playing]"
106,ava.moore@example.com,0336-8765432,Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True,helloi'mavamoore.i'mstudyingarchitectureandhav...,"[studying, building]"
107,logan.thompson@example.com,0407-2345678,Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True,bonjour!jem'appelleloganthompson.j'étudielessc...,[]
108,mia.walker@example.com,0418-7654321,Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True,ciao!i'mmiawalker.<p>i'mstudyingeconomicsandlo...,"[studying, traveling]"

#### 10.	Perform Lemmatization using POS Tagging

In [24]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

In [25]:
def lemmatize_word(word):
    pos_tag = nltk.pos_tag([word])[0][1]  # Get the POS tag
    tag = get_wordnet_pos(pos_tag)  # Convert the POS tag to WordNet POS tag
    if tag is None:
        return word
    else:
        lemmatizer = WordNetLemmatizer()
        return lemmatizer.lemmatize(word, tag)

In [26]:
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return None

In [27]:
df['Lemma'] = df['About'].apply(lemmatize_word)
df

,Email,Phone,Address,URLs,Institute,About,Has_Phone_Number,Clean Text,"Words ending with ""ing""",Lemma
0,(Valid email Removed),0423-1234567,Main Street,www.example.com,Stanford University,I am john doe. i am a software engineer. i lik...,True,Iamjohndoe.iamasoftwareengineer.iliketoplaybas...,[],I am john doe. i am a software engineer. i lik...
1,jane.doe@example.com,555-666-7777,Elm Street,www.example.org,MIT,I am jane doe. <p>i am a doctor.</p> i like to...,False,Iamjanedoe.<p>iamadoctor.</p>iliketoreadbooksa...,[],I am jane doe. <p>i am a doctor.</p> i like to...
2,emma.roberts@example.com,0421-9876543,Oak Street,www.example.com,University of California,<p>hi i'm <strong>emma roberts</strong>. i'm p...,True,<p>hii'm<strong>emmaroberts</strong>.i'mpursui...,"[pursuing, writing]",<p>hi i'm <strong>emma roberts</strong>. i'm p...
3,liam.carter@example.com,0331-3456789,Maple Avenue,www.example.org,University of Texas at Austin,<p>hey there! i'm <strong>liam carter</strong>...,True,<p>heythere!i'm<strong>liamcarter</strong>.i'm...,[majoring],<p>hey there! i'm <strong>liam carter</strong>...
4,ava.collins@example.com,0322-8765432,Cedar Road,www.example.net,Columbia University,<p>hello i'm <strong>ava collins</strong>. i'm...,True,<p>helloi'm<strong>avacollins</strong>.i'mstud...,"[studying, creating]",<p>hello i'm <strong>ava collins</strong>. i'm...
...,...,...,...,...,...,...,...,...,...,...
104,sophia.martin@example.com,0434-9876543,Elm Road,www.example.au,University of Sydney,g'day! i'm sophia martin. i'm pursuing a degre...,True,g'day!i'msophiamartin.i'mpursuingadegreeinbiol...,[pursuing],g'day! i'm sophia martin. i'm pursuing a degre...
105,liam.jackson@example.com,0425-3456789,Oak Lane,www.example.in,Indian Institute of Technology Bombay,hi there! i'm liam jackson. i'm studying compu...,True,hithere!i'mliamjackson.i'mstudyingcomputerengi...,"[studying, engineering, playing]",hi there! i'm liam jackson. i'm studying compu...
106,ava.moore@example.com,0336-8765432,Cedar Street,www.example.de,Technical University of Munich,hello i'm ava moore. i'm studying architectur...,True,helloi'mavamoore.i'mstudyingarchitectureandhav...,"[studying, building]",hello i'm ava moore. i'm studying architectur...
107,logan.thompson@example.com,0407-2345678,Pine Lane,www.example.fr,Paris-Saclay University,bonjour! je m'appelle logan thompson. j'étudie...,True,bonjour!jem'appelleloganthompson.j'étudielessc...,[],bonjour! je m'appelle logan thompson. j'étudie...
108,mia.walker@example.com,0418-7654321,Birch Avenue,www.example.it,University of Milan,ciao! i'm mia walker.<p> i'm studying economic...,True,ciao!i'mmiawalker.<p>i'mstudyingeconomicsandlo...,"[studying, traveling]",ciao! i'm mia walker.<p> i'm studying economic...